# Generated by Django 3.2.8 on 2021-10-23 21:30

import Moove_Assessment_Api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='E-mail address of applicant', max_length=254, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(help_text='First name of applicant', max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Family or surname of applicant', max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Last Name')),
                ('age', models.PositiveIntegerField(help_text='Age of applicant', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(60)], verbose_name='Age')),
                ('address', models.TextField(help_text='Residential or contact address', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Address')),
                ('country', models.CharField(help_text='Country of origin of applicant', max_length=20, validators=[Moove_Assessment_Api.validators.validate_country_name, django.core.validators.MinLengthValidator(2)], verbose_name='Country')),
                ('is_hired', models.BooleanField(help_text='Is applicant already hired?', null=True, verbose_name='Hired status')),
            ],
        ),
    ]
